// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: protos/atomic_issuer.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AtomicIssuerClient is the client API for AtomicIssuer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AtomicIssuerClient interface {
	IssueAtomicVC(ctx context.Context, in *MsgRequestAtomicVC, opts ...grpc.CallOption) (*MsgResponseAtomicVC, error)
}

type atomicIssuerClient struct {
	cc grpc.ClientConnInterface
}

func NewAtomicIssuerClient(cc grpc.ClientConnInterface) AtomicIssuerClient {
	return &atomicIssuerClient{cc}
}

func (c *atomicIssuerClient) IssueAtomicVC(ctx context.Context, in *MsgRequestAtomicVC, opts ...grpc.CallOption) (*MsgResponseAtomicVC, error) {
	out := new(MsgResponseAtomicVC)
	err := c.cc.Invoke(ctx, "/AtomicIssuer.AtomicIssuer/IssueAtomicVC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AtomicIssuerServer is the server API for AtomicIssuer service.
// All implementations must embed UnimplementedAtomicIssuerServer
// for forward compatibility
type AtomicIssuerServer interface {
	IssueAtomicVC(context.Context, *MsgRequestAtomicVC) (*MsgResponseAtomicVC, error)
	mustEmbedUnimplementedAtomicIssuerServer()
}

// UnimplementedAtomicIssuerServer must be embedded to have forward compatible implementations.
type UnimplementedAtomicIssuerServer struct {
}

func (UnimplementedAtomicIssuerServer) IssueAtomicVC(context.Context, *MsgRequestAtomicVC) (*MsgResponseAtomicVC, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueAtomicVC not implemented")
}
func (UnimplementedAtomicIssuerServer) mustEmbedUnimplementedAtomicIssuerServer() {}

// UnsafeAtomicIssuerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AtomicIssuerServer will
// result in compilation errors.
type UnsafeAtomicIssuerServer interface {
	mustEmbedUnimplementedAtomicIssuerServer()
}

func RegisterAtomicIssuerServer(s grpc.ServiceRegistrar, srv AtomicIssuerServer) {
	s.RegisterService(&AtomicIssuer_ServiceDesc, srv)
}

func _AtomicIssuer_IssueAtomicVC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRequestAtomicVC)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AtomicIssuerServer).IssueAtomicVC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AtomicIssuer.AtomicIssuer/IssueAtomicVC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AtomicIssuerServer).IssueAtomicVC(ctx, req.(*MsgRequestAtomicVC))
	}
	return interceptor(ctx, in, info, handler)
}

// AtomicIssuer_ServiceDesc is the grpc.ServiceDesc for AtomicIssuer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AtomicIssuer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AtomicIssuer.AtomicIssuer",
	HandlerType: (*AtomicIssuerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueAtomicVC",
			Handler:    _AtomicIssuer_IssueAtomicVC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/atomic_issuer.proto",
}
